<?php
declare(strict_types=1);
require __DIR__.'/../inc/db.php';require __DIR__.'/../inc/page.php';require __DIR__.'/../inc/order_service.php';require_staff_or_admin();
$message='';$result=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
 require_post_csrf();
 try{
  $customerId=(int)($_POST['customer_id']??0);$cakeId=(int)($_POST['cake_id']??0);$qty=max(1,min(99,(int)($_POST['qty']??1)));
  $options=[];foreach((array)($_POST['options']??[]) as $id)$options[]=['id'=>(int)$id];
  $addons=[];foreach((array)($_POST['addons']??[]) as $id=>$addonQty){$addonQty=(int)$addonQty;if($addonQty>0)$addons[]=['id'=>(int)$id,'qty'=>min(20,$addonQty)];}
  $payload=['cart'=>[['id'=>$cakeId,'qty'=>$qty,'options'=>$options,'addons'=>$addons]],'pickup_date'=>(string)($_POST['pickup_date']??''),'pickup_time'=>(string)($_POST['pickup_time']??''),'payment'=>'cash','customer_note'=>(string)($_POST['customer_note']??'')];
  $result=create_normal_order($pdo,$payload,$customerId,user_id(),'staff_assisted');
 }catch(Throwable $e){error_log('Assisted order failed: '.$e->getMessage());$message=$e instanceof PDOException?'Unable to place the assisted order.':$e->getMessage();}
}
$customers=$pdo->query("SELECT id,name,email,phone FROM users WHERE role='customer' AND is_active=1 AND phone_verified_at IS NOT NULL ORDER BY name")->fetchAll();
$cakes=$pdo->query('SELECT id,name,price,quantity FROM cakes WHERE available=1 ORDER BY name')->fetchAll();
$options=$pdo->query("SELECT co.cake_id,o.id,o.option_type,o.name,o.price_adjustment,o.stock,co.is_required FROM cake_option_compatibility co JOIN cake_options o ON o.id=co.option_id WHERE o.is_active=1 ORDER BY co.cake_id,o.option_type,o.name")->fetchAll();
$addons=$pdo->query('SELECT ca.cake_id,a.id,a.name,a.price,a.quantity FROM cakes_addons ca JOIN addons a ON a.id=ca.addon_id WHERE a.is_active=1 ORDER BY ca.cake_id,a.name')->fetchAll();
page_start('Assisted cash order');
?><main class="container py-4"><div class="d-flex justify-content-between"><div><div class="eyebrow">Staff workspace</div><h1 class="h3">Create assisted cash order</h1><p class="help-text">The selected customer owns the order. Inventory, options, capacity, totals, and claim code use the same checkout service as customer orders.</p></div><a href="unified_orders.php" class="btn btn-outline-primary align-self-start">Orders</a></div><?php if($message):?><div class="alert alert-danger"><?=e($message)?></div><?php endif;?><?php if($result):?><div class="alert alert-success">Order <?=e($result['order_number'])?> was created. <a href="unified_orders.php?search=<?=urlencode($result['order_number'])?>">Open order</a></div><?php endif;?>
<form method="post" class="app-card p-4" id="assisted-form"><?=csrf_field()?><div class="row g-3"><div class="col-md-6"><label class="form-label">Verified customer</label><select name="customer_id" class="form-select" required><option value="">Choose customer</option><?php foreach($customers as $c):?><option value="<?=(int)$c['id']?>"><?=e($c['name'].' - '.$c['phone'])?></option><?php endforeach;?></select></div><div class="col-md-6"><label class="form-label">Cake</label><select name="cake_id" id="cake_id" class="form-select" required><option value="">Choose cake</option><?php foreach($cakes as $cake):?><option value="<?=(int)$cake['id']?>"><?=e($cake['name'])?> - &#8369;<?=number_format((float)$cake['price'],2)?> (<?=(int)$cake['quantity']?> available)</option><?php endforeach;?></select></div><div class="col-md-3"><label class="form-label">Quantity</label><input type="number" name="qty" min="1" max="99" value="1" class="form-control" required></div><div class="col-md-4"><label class="form-label">Pickup date</label><input type="date" name="pickup_date" min="<?=date('Y-m-d')?>" class="form-control" required></div><div class="col-md-3"><label class="form-label">Pickup time</label><select name="pickup_time" id="pickup_time" class="form-select" required><option value="">Choose a date first</option></select></div><div class="col-12"><label class="form-label">Customer note</label><textarea name="customer_note" maxlength="1000" class="form-control"></textarea></div></div><div id="option-groups" class="row g-3 mt-1"></div><button class="btn btn-purple mt-4">Create pending cash order</button></form></main>
<script>const optionRows=<?=json_encode($options,JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT)?>,addonRows=<?=json_encode($addons,JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT)?>;const cake=document.getElementById('cake_id'),groups=document.getElementById('option-groups');function esc(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}function render(){const id=Number(cake.value);groups.innerHTML='';const by={};optionRows.filter(x=>Number(x.cake_id)===id).forEach(x=>(by[x.option_type]??=[]).push(x));Object.entries(by).forEach(([type,rows])=>{const wrap=document.createElement('div');wrap.className='col-md-4';wrap.innerHTML='<label class="form-label">'+esc(type)+'</label><select class="form-select" name="options[]" '+(rows.some(x=>Number(x.is_required)===1)?'required':'')+'><option value="">'+(rows.some(x=>Number(x.is_required)===1)?'Choose one':'None')+'</option>'+rows.map(x=>'<option value="'+x.id+'">'+esc(x.name)+' (&#8369;'+Number(x.price_adjustment).toFixed(2)+')</option>').join('')+'</select>';groups.appendChild(wrap)});addonRows.filter(x=>Number(x.cake_id)===id).forEach(x=>{const wrap=document.createElement('div');wrap.className='col-md-3';wrap.innerHTML='<label class="form-label">'+esc(x.name)+' quantity</label><input class="form-control" type="number" min="0" max="20" value="0" name="addons['+x.id+']">';groups.appendChild(wrap)})}cake.addEventListener('change',render);document.querySelector('[name=pickup_date]').addEventListener('change',async e=>{const s=document.getElementById('pickup_time');s.innerHTML='<option>Loading...</option>';try{const r=await fetch('../availability.php?pickup_date='+encodeURIComponent(e.target.value));const j=await r.json();s.innerHTML='<option value="">Choose a time</option>'+j.slots.map(x=>'<option value="'+x.time+'">'+esc(x.time)+' ('+x.remaining+' remaining)</option>').join('')}catch(_){s.innerHTML='<option value="">Unavailable</option>'}});</script><?php page_end();
