<?php
declare(strict_types=1);require_once __DIR__.'/order_service.php';
function update_order_status(PDO $pdo,int $headerId,string $target,int $actorId,?string $claimCode=null): void { if(!in_array($target,ORDER_STATUSES,true))throw new InvalidArgumentException('Invalid status.');$pdo->beginTransaction();try{$q=$pdo->prepare('SELECT * FROM order_headers WHERE id=? FOR UPDATE');$q->execute([$headerId]);$o=$q->fetch();if(!$o)throw new RuntimeException('Order not found.');$flow=['Pending'=>'Confirmed','Confirmed'=>'Preparing','Preparing'=>'Ready for Pickup','Ready for Pickup'=>'Completed'];if(($flow[$o['status']]??null)!==$target)throw new RuntimeException('Status must follow the order workflow.');if($o['order_type']==='ai'&&$target==='Confirmed'&&(float)$o['total']<=0)throw new RuntimeException('Assign a positive AI cake price before confirmation.');if($target==='Completed'){if(!$claimCode||!$o['claim_code_hash']||!password_verify($claimCode,$o['claim_code_hash']))throw new RuntimeException('The claim code is incorrect.');$payment=$o['payment_method']==='cash'?'paid':$o['payment_status'];}else{$payment=$o['payment_status'];}$pdo->prepare('UPDATE order_headers SET status=?,payment_status=?,claimed_at=IF(?=\'Completed\',NOW(),claimed_at),completed_at=IF(?=\'Completed\',NOW(),completed_at) WHERE id=?')->execute([$target,$payment,$target,$target,$headerId]);$legacy=$o['order_type']==='ai'?'ai_cake_orders':'orders';$legacyId=$o['order_type']==='ai'?$o['ai_order_id']:$o['normal_order_id'];$legacyStatus=match($target){'Preparing'=>'processing','Ready for Pickup'=>'ready',default=>strtolower($target)};$pdo->prepare("UPDATE {$legacy} SET status=?,payment_status=? WHERE id=?")->execute([$legacyStatus,$payment,$legacyId]);$pdo->prepare('INSERT INTO order_status_history(order_header_id,from_status,to_status,actor_user_id) VALUES(?,?,?,?)')->execute([$headerId,$o['status'],$target,$actorId]);$template=match($target){'Confirmed'=>'order_confirmed','Preparing'=>'order_preparing','Ready for Pickup'=>'order_ready','Completed'=>'order_completed',default=>null};if($template!==null)queue_sms($pdo,'order:'.$headerId.':'.strtolower(str_replace(' ','_',$target)),$o['customer_phone'],$template,['order_number'=>$o['order_number']]);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;} }
function set_ai_price(PDO $pdo,int $headerId,float $price,int $actorId): void { if($price<=0)throw new InvalidArgumentException('AI cake price must be greater than zero.');$pdo->beginTransaction();try{$q=$pdo->prepare("SELECT * FROM order_headers WHERE id=? AND order_type='ai' AND status='Pending' FOR UPDATE");$q->execute([$headerId]);$o=$q->fetch();if(!$o)throw new RuntimeException('Only pending AI orders can be priced.');$pdo->prepare('UPDATE order_headers SET subtotal=?,original_total=?,discount_total=0,total=? WHERE id=?')->execute([$price,$price,$price,$headerId]);$pdo->prepare('UPDATE ai_cake_orders SET total=? WHERE id=?')->execute([$price,$o['ai_order_id']]);$pdo->prepare("INSERT INTO order_status_history(order_header_id,from_status,to_status,actor_user_id,note) VALUES(?,'Pending','Pending',?,'AI cake price assigned')")->execute([$headerId,$actorId]);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;} }
function record_legacy_ai_size(PDO $pdo, int $headerId, string $size, int $actorId): void
{
    if (!in_array($size, ['Small', 'Medium', 'Large'], true)) {
        throw new InvalidArgumentException('Select Small, Medium, or Large.');
    }

    $pdo->beginTransaction();
    try {
        $query = $pdo->prepare("SELECT h.id,h.status,h.ai_order_id,a.cake_size FROM order_headers h INNER JOIN ai_cake_orders a ON a.id=h.ai_order_id WHERE h.id=? AND h.order_type='ai' FOR UPDATE");
        $query->execute([$headerId]);
        $order = $query->fetch();
        if (!$order) {
            throw new RuntimeException('AI order not found.');
        }
        if (trim((string) $order['cake_size']) !== '') {
            throw new RuntimeException('This AI cake size is already recorded.');
        }

        $pdo->prepare('UPDATE ai_cake_orders SET cake_size=? WHERE id=?')->execute([$size, $order['ai_order_id']]);
        $pdo->prepare('INSERT INTO order_status_history(order_header_id,from_status,to_status,actor_user_id,note) VALUES(?,?,?,?,?)')->execute([$headerId, $order['status'], $order['status'], $actorId, 'Legacy AI cake size recorded: ' . $size]);
        $pdo->commit();
    } catch (Throwable $error) {
        if ($pdo->inTransaction()) {
            $pdo->rollBack();
        }
        throw $error;
    }
}
function apply_discount(PDO $pdo,int $headerId,string $type,float $value,string $reason,int $actorId): void { if(!in_array($type,['fixed','percentage'],true)||$value<=0||strlen(trim($reason))<3)throw new InvalidArgumentException('Enter a valid discount and reason.');$pdo->beginTransaction();try{$q=$pdo->prepare("SELECT * FROM order_headers WHERE id=? AND status='Pending' FOR UPDATE");$q->execute([$headerId]);$o=$q->fetch();if(!$o)throw new RuntimeException('Discounts are locked after confirmation.');$amount=$type==='percentage'?(float)$o['original_total']*min($value,100)/100:min($value,(float)$o['original_total']);$final=max(0,(float)$o['original_total']-$amount);$pdo->prepare('UPDATE order_headers SET discount_total=?,total=? WHERE id=?')->execute([$amount,$final,$headerId]);$pdo->prepare('INSERT INTO order_discounts(order_header_id,discount_type,discount_value,original_total,discount_amount,final_total,reason,applied_by) VALUES(?,?,?,?,?,?,?,?)')->execute([$headerId,$type,$value,$o['original_total'],$amount,$final,trim($reason),$actorId]);$legacy=$o['order_type']==='ai'?'ai_cake_orders':'orders';$legacyId=$o['order_type']==='ai'?$o['ai_order_id']:$o['normal_order_id'];$pdo->prepare("UPDATE {$legacy} SET total=? WHERE id=?")->execute([$final,$legacyId]);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;} }

function mark_manual_refund(PDO $pdo,int $headerId,int $actorId,string $reference): void { if(strlen(trim($reference))<3)throw new InvalidArgumentException('Enter the manual refund reference or note.');$pdo->beginTransaction();try{$q=$pdo->prepare("SELECT * FROM order_headers WHERE id=? AND status='Cancelled' AND refund_state='refund_required' FOR UPDATE");$q->execute([$headerId]);$o=$q->fetch();if(!$o)throw new RuntimeException('This order does not require a refund.');$pdo->prepare("UPDATE order_headers SET refund_state='refunded',payment_status='refunded' WHERE id=?")->execute([$headerId]);if($o['order_type']==='ai')$pdo->prepare('UPDATE ai_cake_orders SET refund_required=0 WHERE id=?')->execute([$o['ai_order_id']]);else $pdo->prepare("UPDATE orders SET payment_status='refunded' WHERE id=?")->execute([$o['normal_order_id']]);$pdo->prepare("INSERT INTO order_status_history(order_header_id,from_status,to_status,actor_user_id,note) VALUES(?,'Cancelled','Cancelled',?,?)")->execute([$headerId,$actorId,'Manual refund recorded: '.trim($reference)]);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;} }
