<?php
declare(strict_types=1);
require_once __DIR__.'/auth.php';require_once __DIR__.'/notification_service.php';require_once __DIR__.'/env.php';
const ORDER_STATUSES=['Pending','Confirmed','Preparing','Ready for Pickup','Completed','Cancelled'];
function unique_order_number(PDO $pdo,string $prefix='ORD'): string { for($i=0;$i<12;$i++){ $n=$prefix.strtoupper(bin2hex(random_bytes(5)));$q=$pdo->prepare('SELECT 1 FROM order_headers WHERE order_number=?');$q->execute([$n]);if(!$q->fetchColumn())return $n;}throw new RuntimeException('Could not generate an order number.'); }
function claim_encrypt(string $code): string { $key=hash('sha256',(string)env_value('APP_KEY','local-development-key'),true);$iv=random_bytes(12);$tag='';$cipher=openssl_encrypt($code,'aes-256-gcm',$key,OPENSSL_RAW_DATA,$iv,$tag);return base64_encode($iv.$tag.$cipher); }
function claim_decrypt(string $value): string { $raw=base64_decode($value,true);if($raw===false||strlen($raw)<29)return '';$key=hash('sha256',(string)env_value('APP_KEY','local-development-key'),true);return (string)openssl_decrypt(substr($raw,28),'aes-256-gcm',$key,OPENSSL_RAW_DATA,substr($raw,0,12),substr($raw,12,16)); }
function canonical_status(string $status): string { return match(strtolower(trim($status))){'confirmed'=>'Confirmed','processing','preparing'=>'Preparing','ready','ready for pickup'=>'Ready for Pickup','completed'=>'Completed','cancelled','canceled'=>'Cancelled',default=>'Pending'}; }
function validate_pickup_schedule(string $date,string $time): void {
 if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date)||!preg_match('/^(?:[01]\d|2[0-3]):[0-5]\d$/',$time))throw new InvalidArgumentException('Choose a valid pickup schedule.');
 $pickup=DateTimeImmutable::createFromFormat('!Y-m-d H:i',$date.' '.$time);$errors=DateTimeImmutable::getLastErrors();
 if(!$pickup||($errors!==false&&($errors['warning_count']>0||$errors['error_count']>0)))throw new InvalidArgumentException('Choose a valid pickup schedule.');
 if($pickup<=new DateTimeImmutable('now'))throw new InvalidArgumentException('Pickup date and time must be in the future.');
}
function reserve_pickup(PDO $pdo,string $date,string $time,int $headerId): void { validate_pickup_schedule($date,$time);$q=$pdo->prepare('SELECT * FROM pickup_capacities WHERE pickup_date=? AND pickup_time=? AND active=1 FOR UPDATE');$q->execute([$date,$time]);$slot=$q->fetch();if(!$slot)throw new RuntimeException('That pickup slot is not configured. Please choose another.');if((int)$slot['reserved']>=(int)$slot['capacity'])throw new RuntimeException('That pickup slot is full.');$pdo->prepare('UPDATE pickup_capacities SET reserved=reserved+1 WHERE id=?')->execute([$slot['id']]);$pdo->prepare("INSERT INTO order_reservations(order_header_id,resource_type,resource_id,quantity) VALUES(?,'pickup_slot',?,1)")->execute([$headerId,$slot['id']]); }
function validated_cake_options(PDO $pdo,int $cakeId,array $submitted,int $cakeQty): array { $q=$pdo->prepare('SELECT o.*,co.is_required FROM cake_option_compatibility co JOIN cake_options o ON o.id=co.option_id WHERE co.cake_id=? AND o.is_active=1 FOR UPDATE');$q->execute([$cakeId]);$available=$q->fetchAll();$byId=[];$requiredTypes=[];foreach($available as $o){$byId[(int)$o['id']]=$o;if((int)$o['is_required']===1)$requiredTypes[$o['option_type']]=true;}$chosen=[];$chosenTypes=[];foreach($submitted as $raw){$id=(int)($raw['id']??0);if(!$id||!isset($byId[$id]))throw new RuntimeException('A selected cake option is unavailable or incompatible.');$o=$byId[$id];if(isset($chosenTypes[$o['option_type']]))throw new RuntimeException('Choose only one option for each option type.');if($o['stock']!==null&&(int)$o['stock']<$cakeQty)throw new RuntimeException($o['name'].' is out of stock.');$chosen[]=$o;$chosenTypes[$o['option_type']]=true;}foreach($requiredTypes as $type=>$_)if(empty($chosenTypes[$type]))throw new RuntimeException('Choose a required '.strtolower($type).' option.');return $chosen; }
function create_normal_order(PDO $pdo,array $payload,int $uid,?int $createdByUserId=null,string $source='customer'): array {
 if(!in_array($source,['customer','staff_assisted'],true))throw new InvalidArgumentException('Invalid order source.');
 $createdByUserId=$createdByUserId??$uid;
 $cart=$payload['cart']??[];if(!is_array($cart)||!$cart)throw new InvalidArgumentException('Your cart is empty.');$date=(string)($payload['pickup_date']??'');$time=(string)($payload['pickup_time']??'');validate_pickup_schedule($date,$time);
 $u=$pdo->prepare("SELECT * FROM users WHERE id=? AND role='customer' AND is_active=1");$u->execute([$uid]);$user=$u->fetch();if(!$user)throw new RuntimeException('Customer account is not active.');if(empty($user['phone_verified_at']))throw new RuntimeException('The customer must verify their phone before an order can be placed.');$store=$pdo->query('SELECT * FROM stores WHERE is_active=1 ORDER BY id LIMIT 1')->fetch();if(!$store)throw new RuntimeException('No pickup shop is configured.');
 $pdo->beginTransaction();try{$lines=[];$subtotal=0;$cakeDemand=[];$cakeRows=[];$optionDemand=[];
  foreach($cart as $line){$cakeId=(int)($line['id']??0);$qty=min(99,max(1,(int)($line['qty']??1)));$q=$pdo->prepare('SELECT id,name,price,quantity,available FROM cakes WHERE id=? FOR UPDATE');$q->execute([$cakeId]);$cake=$q->fetch();if(!$cake||(int)$cake['available']!==1)throw new RuntimeException('A selected cake is no longer available.');$options=validated_cake_options($pdo,$cakeId,(array)($line['options']??[]),$qty);$optionUnit=0;foreach($options as $option){$optionUnit+=(float)$option['price_adjustment'];if($option['stock']!==null)$optionDemand[(int)$option['id']]=($optionDemand[(int)$option['id']]??0)+$qty;}$unit=(float)$cake['price'];$subtotal+=($unit+$optionUnit)*$qty;$cakeDemand[$cakeId]=($cakeDemand[$cakeId]??0)+$qty;$cakeRows[$cakeId]=$cake;$lines[]=['cake'=>$cake,'qty'=>$qty,'unit'=>$unit,'addons'=>$line['addons']??[],'options'=>$options];}
  foreach($cakeDemand as $cakeId=>$required){if((int)$cakeRows[$cakeId]['quantity']<$required)throw new RuntimeException($cakeRows[$cakeId]['name'].' does not have enough stock.');}
  foreach($optionDemand as $optionId=>$required){$oq=$pdo->prepare('SELECT name,stock FROM cake_options WHERE id=? FOR UPDATE');$oq->execute([$optionId]);$orow=$oq->fetch();if(!$orow||$orow['stock']===null||(int)$orow['stock']<$required)throw new RuntimeException(($orow['name']??'A selected option').' does not have enough stock.');}
  $number=unique_order_number($pdo);$claim=(string)random_int(100000,999999);$payment=strtolower((string)($payload['payment']??'cash'))==='gcash'?'gcash':'cash';
  $q=$pdo->prepare("INSERT INTO orders(order_number,customer_name,customer_email,customer_phone,total,payment,addons,personalization,pickup_date,pickup_time,store_name,status,is_ai,payment_status) VALUES(?,?,?,?,?,?,?, ?,?,?,?,'pending',0,?)");$q->execute([$number,$user['name'],$user['email'],$user['phone'],$subtotal,$payment,'[]','[]',$date,$time,$store['name'],$payment==='gcash'?'pending':'unpaid']);$legacyId=(int)$pdo->lastInsertId();
  $note=trim((string)($payload['customer_note']??''));if(mb_strlen($note)>1000)throw new InvalidArgumentException('Customer note is too long.');
  $q=$pdo->prepare("INSERT INTO order_headers(order_number,user_id,created_by_user_id,normal_order_id,order_type,order_source,customer_name,customer_email,customer_phone,pickup_date,pickup_time,store_id,store_name,payment_method,payment_status,subtotal,original_total,total,customer_note,claim_code_hash,claim_code_cipher) VALUES(?,?,?,?,'normal',?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");$q->execute([$number,$uid,$createdByUserId,$legacyId,$source,$user['name'],$user['email'],$user['phone'],$date,$time,$store['id'],$store['name'],$payment,$payment==='gcash'?'pending':'unpaid',$subtotal,$subtotal,$subtotal,$note,password_hash($claim,PASSWORD_DEFAULT),claim_encrypt($claim)]);$headerId=(int)$pdo->lastInsertId();reserve_pickup($pdo,$date,$time,$headerId);
  $item=$pdo->prepare('INSERT INTO order_items(order_id,cake_id,qty,price,is_ai) VALUES(?,?,?,?,0)');
  foreach($lines as $line){$item->execute([$legacyId,$line['cake']['id'],$line['qty'],$line['unit']]);$itemId=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE cakes SET quantity=quantity-? WHERE id=?')->execute([$line['qty'],$line['cake']['id']]);$pdo->prepare("INSERT INTO order_reservations(order_header_id,resource_type,resource_id,quantity) VALUES(?,'cake',?,?)")->execute([$headerId,$line['cake']['id'],$line['qty']]);
   foreach((array)$line['options'] as $option){$stockQty=$line['qty'];if($option['stock']!==null){$pdo->prepare('UPDATE cake_options SET stock=stock-? WHERE id=?')->execute([$stockQty,$option['id']]);$pdo->prepare("INSERT INTO order_reservations(order_header_id,resource_type,resource_id,quantity) VALUES(?,'option',?,?)")->execute([$headerId,$option['id'],$stockQty]);}$pdo->prepare('INSERT INTO order_item_options(order_item_id,option_id,option_type,option_name,price_snapshot,quantity) VALUES(?,?,?,?,?,?)')->execute([$itemId,$option['id'],$option['option_type'],$option['name'],$option['price_adjustment'],$stockQty]);}
   $seenAddons=[];
   foreach((array)$line['addons'] as $a){
    $aid=(int)($a['id']??0);
    if($aid<=0||isset($seenAddons[$aid]))throw new RuntimeException('An add-on selection is invalid or duplicated.');
    $seenAddons[$aid]=true;
    // Customer carts receive one add-on per cake unit. Staff-assisted orders may set an explicit total quantity.
    if($source==='staff_assisted'){
     $requested=(int)($a['qty']??0);
     if($requested<1||$requested>20)throw new RuntimeException('Add-on quantity must be between 1 and 20.');
     $aqty=$requested;
    }else{$aqty=$line['qty'];}
    $qa=$pdo->prepare('SELECT a.* FROM cakes_addons ca JOIN addons a ON a.id=ca.addon_id WHERE ca.cake_id=? AND a.id=? AND a.is_active=1 FOR UPDATE');
    $qa->execute([$line['cake']['id'],$aid]);
    $addon=$qa->fetch();
    if(!$addon||(int)$addon['quantity']<$aqty)throw new RuntimeException('An add-on is unavailable or does not have enough stock.');
    $subtotal+=(float)$addon['price']*$aqty;
    $newStock=(int)$addon['quantity']-$aqty;
    $pdo->prepare('UPDATE addons SET quantity=? WHERE id=?')->execute([$newStock,$aid]);
    $pdo->prepare('INSERT INTO addon_inventory_adjustments(addon_id,quantity_change,resulting_stock,reason,actor_user_id) VALUES(?,?,?,?,?)')->execute([$aid,-$aqty,$newStock,'Reserved for order '.$number,$createdByUserId]);
    $pdo->prepare("INSERT INTO order_reservations(order_header_id,resource_type,resource_id,quantity) VALUES(?,'addon',?,?)")->execute([$headerId,$aid,$aqty]);
    $pdo->prepare("INSERT INTO order_item_options(order_item_id,option_id,option_type,option_name,price_snapshot,quantity) VALUES(?,NULL,'Add-on',?,?,?)")->execute([$itemId,$addon['name'],$addon['price'],$aqty]);
   }
  }
  $pdo->prepare('UPDATE orders SET total=? WHERE id=?')->execute([$subtotal,$legacyId]);$pdo->prepare('UPDATE order_headers SET subtotal=?,original_total=?,total=? WHERE id=?')->execute([$subtotal,$subtotal,$subtotal,$headerId]);
  $historyNote=$source==='staff_assisted'?'Assisted cash order created by staff':'Order placed by customer';$pdo->prepare("INSERT INTO order_status_history(order_header_id,to_status,actor_user_id,note) VALUES(?,'Pending',?,?)")->execute([$headerId,$createdByUserId,$historyNote]);$pdo->commit();return ['id'=>$headerId,'order_number'=>$number,'total'=>$subtotal,'claim_code'=>$claim];
 }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
}
function restore_reservations(PDO $pdo,int $headerId): void { $q=$pdo->prepare('SELECT * FROM order_headers WHERE id=? FOR UPDATE');$q->execute([$headerId]);$h=$q->fetch();if(!$h||$h['reservations_restored_at'])return;$r=$pdo->prepare('SELECT * FROM order_reservations WHERE order_header_id=? AND restored_at IS NULL FOR UPDATE');$r->execute([$headerId]);foreach($r as $x){$table=match($x['resource_type']){'cake'=>'cakes','addon'=>'addons','option'=>'cake_options','pickup_slot'=>'pickup_capacities','ai_capacity'=>'ai_capacities'};$pdo->prepare("UPDATE {$table} SET ".(in_array($x['resource_type'],['pickup_slot','ai_capacity'],true)?'reserved=GREATEST(reserved-?,0)':($x['resource_type']==='option'?'stock=stock+?':'quantity=quantity+?'))." WHERE id=?")->execute([$x['quantity'],$x['resource_id']]);if($x['resource_type']==='addon'){$s=$pdo->prepare('SELECT quantity FROM addons WHERE id=?');$s->execute([$x['resource_id']]);$pdo->prepare('INSERT INTO addon_inventory_adjustments(addon_id,quantity_change,resulting_stock,reason,actor_user_id) VALUES(?,?,?,?,?)')->execute([$x['resource_id'],$x['quantity'],(int)$s->fetchColumn(),'Restored after cancellation of '.$h['order_number'],$h['cancelled_by']??null]);}}$pdo->prepare('UPDATE order_reservations SET restored_at=NOW() WHERE order_header_id=? AND restored_at IS NULL')->execute([$headerId]);$pdo->prepare('UPDATE order_headers SET reservations_restored_at=NOW() WHERE id=?')->execute([$headerId]); }
function cancel_order(PDO $pdo,int $headerId,int $actorId,string $reason,bool $staff=false): void { if(strlen(trim($reason))<3)throw new InvalidArgumentException('A cancellation reason is required.');$pdo->beginTransaction();try{$q=$pdo->prepare('SELECT * FROM order_headers WHERE id=? FOR UPDATE');$q->execute([$headerId]);$h=$q->fetch();if(!$h)throw new RuntimeException('Order not found.');if(!$staff&&(int)$h['user_id']!==$actorId)throw new RuntimeException('You cannot cancel this order.');$allowed=$staff?['Pending','Confirmed','Preparing','Ready for Pickup']:['Pending'];if(!in_array($h['status'],$allowed,true))throw new RuntimeException('This order can no longer be cancelled.');restore_reservations($pdo,$headerId);$refund=$h['payment_status']==='paid'?'refund_required':'none';$pdo->prepare("UPDATE order_headers SET status='Cancelled',cancellation_reason=?,cancelled_by=?,cancelled_at=NOW(),refund_state=? WHERE id=?")->execute([trim($reason),$actorId,$refund,$headerId]);$legacyTable=$h['order_type']==='ai'?'ai_cake_orders':'orders';$legacyId=$h['order_type']==='ai'?$h['ai_order_id']:$h['normal_order_id'];$pdo->prepare("UPDATE {$legacyTable} SET status='cancelled'".($h['order_type']==='ai'?',refund_required=?':'')." WHERE id=?")->execute($h['order_type']==='ai'?[$refund==='refund_required'?1:0,$legacyId]:[$legacyId]);$pdo->prepare("INSERT INTO order_status_history(order_header_id,from_status,to_status,actor_user_id,note) VALUES(?,?,'Cancelled',?,?)")->execute([$headerId,$h['status'],$actorId,trim($reason)]);queue_sms($pdo,'order:'.$headerId.':cancelled',$h['customer_phone'],'order_cancelled',['order_number'=>$h['order_number']]);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;} }
