ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS payment_status VARCHAR(30) DEFAULT 'unpaid',
  ADD COLUMN IF NOT EXISTS payment_reference TEXT NULL,
  ADD COLUMN IF NOT EXISTS payment_invoice_id VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS paid_at DATETIME NULL;

ALTER TABLE ai_cake_orders
  ADD COLUMN IF NOT EXISTS payment_status VARCHAR(30) DEFAULT 'unpaid',
  ADD COLUMN IF NOT EXISTS payment_reference TEXT NULL,
  ADD COLUMN IF NOT EXISTS payment_invoice_id VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS paid_at DATETIME NULL,
  ADD COLUMN IF NOT EXISTS paid_sms_sent TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS paid_sms_sent_at DATETIME NULL;
